eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8762/eureka/,http://${eureka.instance.hostname}:8763/eureka/

---
spring:
  profiles: peer1
server:
  port: 8761

---
spring:
  profiles: peer2
server:
  port: 8762

---
spring:
  profiles: peer3
server:
  port: 8763